import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,unlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join,dirname,resolve} from 'node:path';import {spawnSync} from 'node:child_process';
import {reviewPR,prMarkdown} from '../src/pr-review.mjs';
function fixture(){const cwd=mkdtempSync(join(tmpdir(),'monna-pr-test-'));const git=(...args)=>{const r=spawnSync('git',['-c','user.name=Test','-c','user.email=test@example.invalid','-c','commit.gpgsign=false',...args],{cwd,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};git('init','--initial-branch=main');const write=(p,text)=>{mkdirSync(dirname(join(cwd,p)),{recursive:true});writeFileSync(join(cwd,p),text);};const commit=()=>{git('add','.');git('commit','--allow-empty','-m','fixture');return git('rev-parse','HEAD');};write('README.md','fixture');const base=commit();return {cwd,git,write,commit,base};}
const opts=(f,base,head)=>({cwd:f.cwd,base,head,repository:'example/project'});
test('PR discovers added config, creates empty baseline and actionable exact links',()=>{const f=fixture();f.write('.claude/settings.json','{\n"permissions":{"allow":["Bash(*)"]}\n}');const head=f.commit();const r=reviewPR(opts(f,f.base,head));assert.equal(r.exitCode,1);assert.equal(r.files[0].beforePresent,false);const md=prMarkdown(r);assert.match(md,/ALLOW_ADDED/);assert.match(md,/Why review:/);assert.match(md,/Action:/);assert.match(md,/synthetic empty baseline/);assert.ok(md.includes(`/blob/${head}/.claude/settings.json#L2`));assert.ok(!md.includes('Bash(*)'));});
test('PR deletion detects removed approval and deny rules',()=>{const f=fixture();f.write('.claude/settings.json','{"permissions":{"deny":["Read"],"ask":["Bash"]}}');const base=f.commit();unlinkSync(join(f.cwd,'.claude/settings.json'));const r=reviewPR(opts(f,base,f.commit()));assert.deepEqual(r.files[0].report.findings.map(x=>x.code),['DENY_REMOVED','ASK_REMOVED']);assert.match(prMarkdown(r),/file removed/);});
test('PR uses merge base rather than unrelated changes added to base branch',()=>{const f=fixture();f.git('checkout','-b','proposal');f.write('.claude/settings.json','{"permissions":{"allow":["Write"]}}');const head=f.commit();f.git('checkout','main');f.write('.mcp.json','{"mcpServers":{"other":{"command":"node"}}}');const base=f.commit();const r=reviewPR(opts(f,base,head));assert.equal(r.mergeBase,f.base);assert.equal(r.files.length,1);assert.equal(r.files[0].path,'.claude/settings.json');});
test('PR distinguishes no supported changes and malformed/unsupported inputs',()=>{const f=fixture();f.write('README.md','changed');assert.equal(reviewPR(opts(f,f.base,f.commit())).verdict,'no_supported_config_changes');f.write('.claude/settings.json','{"permissions":{},"permissions":{}}');f.write('.codex/config.toml','sandbox_mode="read-only"');const r=reviewPR(opts(f,f.base,f.commit()));assert.equal(r.exitCode,2);assert.equal(r.files.find(x=>x.path==='.codex/config.toml').status,'unsupported');assert.equal(r.files.find(x=>x.path==='.claude/settings.json').status,'error');});
test('PR treats rename as deletion and addition',()=>{const f=fixture();f.write('.mcp.json','{"mcpServers":{"a":{"command":"node"}}}');const base=f.commit();f.git('mv','.mcp.json','nested.mcp.json');const r=reviewPR(opts(f,base,f.commit()));assert.equal(r.files[0].report.findings[0].code,'SERVER_REMOVED');assert.equal(r.files.length,1);});
test('PR rejects hostile refs and missing history without echoing their contents',()=>{const f=fixture();assert.throws(()=>reviewPR(opts(f,'--help',f.base)),/Invalid commit/);assert.throws(()=>reviewPR(opts(f,'a'.repeat(40),f.base)),/Git objects unavailable/);});
test('PR encodes hostile path text in links, never echoes configuration values',()=>{const f=fixture();f.write('x](/.mcp.json','{"mcpServers":{"a":{"url":"https://example.invalid/?token=CANARY_NOT_REAL"}}}');const r=reviewPR(opts(f,f.base,f.commit()));const md=prMarkdown(r);assert.ok(md.includes('x%5D(/.mcp.json')===false);assert.ok(!md.includes('CANARY_NOT_REAL'));});
test('PR action event emits summary and fails for review; refuses privileged event',()=>{const f=fixture();f.write('.claude/settings.json','{"permissions":{"defaultMode":"bypassPermissions"}}');const head=f.commit();const event=join(f.cwd,'event.json'),summary=join(f.cwd,'summary.md');writeFileSync(event,JSON.stringify({pull_request:{base:{sha:f.base,repo:{full_name:'example/project'}},head:{sha:head}}}));const env={...process.env,GITHUB_WORKSPACE:f.cwd,GITHUB_REPOSITORY:'example/project',GITHUB_EVENT_NAME:'pull_request',GITHUB_EVENT_PATH:event,GITHUB_STEP_SUMMARY:summary,RUNNER_TEMP:f.cwd};const runner=resolve('pr-runner.mjs');const r=spawnSync(process.execPath,[runner],{env,encoding:'utf8'});assert.equal(r.status,1);assert.match(readFileSync(summary,'utf8'),/MODE_CHANGED/);const denied=spawnSync(process.execPath,[runner],{env:{...env,GITHUB_EVENT_NAME:'pull_request_target'},encoding:'utf8'});assert.equal(denied.status,2);});
